# Site settings
title: Georgi Pehlivanov personal web site.
description: This is my personal blog and my online resume.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Georgi Pehlivanov
user_description: Junior Java Developer.... 
user_title: Software Developer
email: georgi.pehlivanov07@gmail.com
twitter_username: https://twitter.com/PehlivanovG
github_username:  GPehlivanov
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
